//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIACinema.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarouselMovie", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CarouselMovie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CarouselMovieIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CarouselMovieId {
            get {
                return this.CarouselMovieIdField;
            }
            set {
                if ((this.CarouselMovieIdField.Equals(value) != true)) {
                    this.CarouselMovieIdField = value;
                    this.RaisePropertyChanged("CarouselMovieId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MovieURL {
            get {
                return this.MovieURLField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieURLField, value) != true)) {
                    this.MovieURLField = value;
                    this.RaisePropertyChanged("MovieURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MovieDescription {
            get {
                return this.MovieDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieDescriptionField, value) != true)) {
                    this.MovieDescriptionField = value;
                    this.RaisePropertyChanged("MovieDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MovieIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartTimeField;
        
        private int DurationInMinutesField;
        
        private double TicketPriceField;
        
        private int CinemaHallIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VIACinema.ServiceReference1.CinemaHall CinemaHallField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MovieId {
            get {
                return this.MovieIdField;
            }
            set {
                if ((this.MovieIdField.Equals(value) != true)) {
                    this.MovieIdField = value;
                    this.RaisePropertyChanged("MovieId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MovieName {
            get {
                return this.MovieNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieNameField, value) != true)) {
                    this.MovieNameField = value;
                    this.RaisePropertyChanged("MovieName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MovieDescription {
            get {
                return this.MovieDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieDescriptionField, value) != true)) {
                    this.MovieDescriptionField = value;
                    this.RaisePropertyChanged("MovieDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MovieImage {
            get {
                return this.MovieImageField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieImageField, value) != true)) {
                    this.MovieImageField = value;
                    this.RaisePropertyChanged("MovieImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartTimeField, value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int DurationInMinutes {
            get {
                return this.DurationInMinutesField;
            }
            set {
                if ((this.DurationInMinutesField.Equals(value) != true)) {
                    this.DurationInMinutesField = value;
                    this.RaisePropertyChanged("DurationInMinutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double TicketPrice {
            get {
                return this.TicketPriceField;
            }
            set {
                if ((this.TicketPriceField.Equals(value) != true)) {
                    this.TicketPriceField = value;
                    this.RaisePropertyChanged("TicketPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int CinemaHallId {
            get {
                return this.CinemaHallIdField;
            }
            set {
                if ((this.CinemaHallIdField.Equals(value) != true)) {
                    this.CinemaHallIdField = value;
                    this.RaisePropertyChanged("CinemaHallId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public VIACinema.ServiceReference1.CinemaHall CinemaHall {
            get {
                return this.CinemaHallField;
            }
            set {
                if ((object.ReferenceEquals(this.CinemaHallField, value) != true)) {
                    this.CinemaHallField = value;
                    this.RaisePropertyChanged("CinemaHall");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CinemaHall", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CinemaHall : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CinemaHallIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CinemaHallNameField;
        
        private int NumberOfSeatsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CinemaHallId {
            get {
                return this.CinemaHallIdField;
            }
            set {
                if ((this.CinemaHallIdField.Equals(value) != true)) {
                    this.CinemaHallIdField = value;
                    this.RaisePropertyChanged("CinemaHallId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CinemaHallName {
            get {
                return this.CinemaHallNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CinemaHallNameField, value) != true)) {
                    this.CinemaHallNameField = value;
                    this.RaisePropertyChanged("CinemaHallName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumberOfSeats {
            get {
                return this.NumberOfSeatsField;
            }
            set {
                if ((this.NumberOfSeatsField.Equals(value) != true)) {
                    this.NumberOfSeatsField = value;
                    this.RaisePropertyChanged("NumberOfSeats");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetCarouselMoviesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarouselMovies", ReplyAction="*")]
        VIACinema.ServiceReference1.GetCarouselMoviesResponse GetCarouselMovies(VIACinema.ServiceReference1.GetCarouselMoviesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarouselMovies", ReplyAction="*")]
        System.Threading.Tasks.Task<VIACinema.ServiceReference1.GetCarouselMoviesResponse> GetCarouselMoviesAsync(VIACinema.ServiceReference1.GetCarouselMoviesRequest request);
        
        // CODEGEN: Generating message contract since element name GetMoviesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovies", ReplyAction="*")]
        VIACinema.ServiceReference1.GetMoviesResponse GetMovies(VIACinema.ServiceReference1.GetMoviesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovies", ReplyAction="*")]
        System.Threading.Tasks.Task<VIACinema.ServiceReference1.GetMoviesResponse> GetMoviesAsync(VIACinema.ServiceReference1.GetMoviesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarouselMoviesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarouselMovies", Namespace="http://tempuri.org/", Order=0)]
        public VIACinema.ServiceReference1.GetCarouselMoviesRequestBody Body;
        
        public GetCarouselMoviesRequest() {
        }
        
        public GetCarouselMoviesRequest(VIACinema.ServiceReference1.GetCarouselMoviesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCarouselMoviesRequestBody {
        
        public GetCarouselMoviesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarouselMoviesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarouselMoviesResponse", Namespace="http://tempuri.org/", Order=0)]
        public VIACinema.ServiceReference1.GetCarouselMoviesResponseBody Body;
        
        public GetCarouselMoviesResponse() {
        }
        
        public GetCarouselMoviesResponse(VIACinema.ServiceReference1.GetCarouselMoviesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCarouselMoviesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VIACinema.ServiceReference1.CarouselMovie[] GetCarouselMoviesResult;
        
        public GetCarouselMoviesResponseBody() {
        }
        
        public GetCarouselMoviesResponseBody(VIACinema.ServiceReference1.CarouselMovie[] GetCarouselMoviesResult) {
            this.GetCarouselMoviesResult = GetCarouselMoviesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMoviesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovies", Namespace="http://tempuri.org/", Order=0)]
        public VIACinema.ServiceReference1.GetMoviesRequestBody Body;
        
        public GetMoviesRequest() {
        }
        
        public GetMoviesRequest(VIACinema.ServiceReference1.GetMoviesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMoviesRequestBody {
        
        public GetMoviesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMoviesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMoviesResponse", Namespace="http://tempuri.org/", Order=0)]
        public VIACinema.ServiceReference1.GetMoviesResponseBody Body;
        
        public GetMoviesResponse() {
        }
        
        public GetMoviesResponse(VIACinema.ServiceReference1.GetMoviesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMoviesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VIACinema.ServiceReference1.Movie[] GetMoviesResult;
        
        public GetMoviesResponseBody() {
        }
        
        public GetMoviesResponseBody(VIACinema.ServiceReference1.Movie[] GetMoviesResult) {
            this.GetMoviesResult = GetMoviesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : VIACinema.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<VIACinema.ServiceReference1.WebServiceSoap>, VIACinema.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VIACinema.ServiceReference1.GetCarouselMoviesResponse VIACinema.ServiceReference1.WebServiceSoap.GetCarouselMovies(VIACinema.ServiceReference1.GetCarouselMoviesRequest request) {
            return base.Channel.GetCarouselMovies(request);
        }
        
        public VIACinema.ServiceReference1.CarouselMovie[] GetCarouselMovies() {
            VIACinema.ServiceReference1.GetCarouselMoviesRequest inValue = new VIACinema.ServiceReference1.GetCarouselMoviesRequest();
            inValue.Body = new VIACinema.ServiceReference1.GetCarouselMoviesRequestBody();
            VIACinema.ServiceReference1.GetCarouselMoviesResponse retVal = ((VIACinema.ServiceReference1.WebServiceSoap)(this)).GetCarouselMovies(inValue);
            return retVal.Body.GetCarouselMoviesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VIACinema.ServiceReference1.GetCarouselMoviesResponse> VIACinema.ServiceReference1.WebServiceSoap.GetCarouselMoviesAsync(VIACinema.ServiceReference1.GetCarouselMoviesRequest request) {
            return base.Channel.GetCarouselMoviesAsync(request);
        }
        
        public System.Threading.Tasks.Task<VIACinema.ServiceReference1.GetCarouselMoviesResponse> GetCarouselMoviesAsync() {
            VIACinema.ServiceReference1.GetCarouselMoviesRequest inValue = new VIACinema.ServiceReference1.GetCarouselMoviesRequest();
            inValue.Body = new VIACinema.ServiceReference1.GetCarouselMoviesRequestBody();
            return ((VIACinema.ServiceReference1.WebServiceSoap)(this)).GetCarouselMoviesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VIACinema.ServiceReference1.GetMoviesResponse VIACinema.ServiceReference1.WebServiceSoap.GetMovies(VIACinema.ServiceReference1.GetMoviesRequest request) {
            return base.Channel.GetMovies(request);
        }
        
        public VIACinema.ServiceReference1.Movie[] GetMovies() {
            VIACinema.ServiceReference1.GetMoviesRequest inValue = new VIACinema.ServiceReference1.GetMoviesRequest();
            inValue.Body = new VIACinema.ServiceReference1.GetMoviesRequestBody();
            VIACinema.ServiceReference1.GetMoviesResponse retVal = ((VIACinema.ServiceReference1.WebServiceSoap)(this)).GetMovies(inValue);
            return retVal.Body.GetMoviesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VIACinema.ServiceReference1.GetMoviesResponse> VIACinema.ServiceReference1.WebServiceSoap.GetMoviesAsync(VIACinema.ServiceReference1.GetMoviesRequest request) {
            return base.Channel.GetMoviesAsync(request);
        }
        
        public System.Threading.Tasks.Task<VIACinema.ServiceReference1.GetMoviesResponse> GetMoviesAsync() {
            VIACinema.ServiceReference1.GetMoviesRequest inValue = new VIACinema.ServiceReference1.GetMoviesRequest();
            inValue.Body = new VIACinema.ServiceReference1.GetMoviesRequestBody();
            return ((VIACinema.ServiceReference1.WebServiceSoap)(this)).GetMoviesAsync(inValue);
        }
    }
}
